---
- name: Deployment Playbook
  hosts: all
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Ping the server to check connectivity
      ansible.builtin.ping:
