name: Output workflow
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set_tag.outputs.tag }}
      release_date: ${{ steps.set_tag.outputs.release_date }}
    steps:
      - name: Compute image tag
        id: set_tag
        run: |
          echo "release_date=$(date +%d-%b-%Y)"
          echo "tag=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy image
        run: |
          echo "Deploying image with tag ${{ needs.build.outputs.image_tag }}"
          echo "The version was realeased on ${{ needs.build.outputs.release_date }}"
