name: Deploy Application

on:
    workflow_call:
        inputs:
            DOCKER_IMAGE:
                description: "Docker image to deploy"
                required: true
                default: "ahagbes/calculator-backend:latest"
                type: string
            SERVICE_NAME:
                description: "Service name (e.g., backend, frontend)"
                required: true
                default: "backend"
                type: string
jobs:
    Deploy:
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repository
              run: |
                  echo "Service Name: ${{ inputs.SERVICE_NAME }}"
                  echo "Docker Image: ${{ inputs.DOCKER_IMAGE }}"
