name: Deploy Application

on:
    workflow_call:
        inputs:
            docker_image:
                description: "Docker image to deploy"
                required: true
                type: string
            service_name:
                description: "Service name (e.g., backend, frontend)"
                required: true
                type: string
        secrets:
            SERVER_HOST:
                description: "The server host address"
                required: true
            SERVER_USER:
                description: "The server user name"
                required: true
            SSH_PRIVATE_KEY:
                description: "SSH private key for server access"
                required: true
jobs:
    Deploy:
        runs-on: ubuntu-24.04

        steps:
            - name: Checkout repository
              uses: actions/checkout@v6.0.1
              with:
                  repository: hanatole/calculator-deployment
                  ref: main

            - name: Deploy application using Ansible
              uses: dawidd6/action-ansible-playbook@v6
              with:
                  playbook: playbook.yml
                  inventory: |
                      [all]
                      ${{ secrets.SERVER_HOST }} ansible_user=${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SSH_PRIVATE_KEY }}
